# Generated by Django 5.2 on 2025-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
