# Generated by Django 5.2 on 2025-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_tag_files_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='category',
        ),
        migrations.AddField(
            model_name='files',
            name='categories',
            field=models.ManyToManyField(blank=True, to='files.category'),
        ),
    ]
