# Generated by Django 5.1.7 on 2025-03-27 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_files_author_alter_files_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='files.category'),
        ),
    ]
