# Generated by Django 5.1.7 on 2025-04-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
